[project]
name = "testinvoke4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "invoke>=2.2.0",
    "iterative-stratification>=0.1.9",
    "scikit-learn>=1.5.2",
    "scikit-multilearn-ng>=0.0.8",
]
